---
title: "Beach BIA Biodiversity BIA"
author: "Derek Li"
date: "2025-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(sf)
library(leaflet)
library(dplyr)
```

```{r}
data.dir <- gsub('/code', '/data', getwd())

# Reading in all data
BIA_data <- st_read(paste0(data.dir, "/data/BIAshapes/Business Improvement Areas Data - 4326.shp"))

beach_park <- st_read(paste0(data.dir, "/data/beach_shapes/WoodbineBeach.shp"))

trees <- st_read(paste0(data.dir, "/data/trees/CROPPED_TOPO_TREE_WGS84.shp"))

inaturalist_df <- read.csv(paste0(data.dir, "/data/inaturalist/observations.csv"))

water <- st_read(paste0(data.dir, "/data/waterbodies/TOPO_Waterbody_WGS84.shp"))

nbhd <- st_read(paste0(data.dir, "/data/neighbourhoods/Neighbourhoods - 4326.shp"))
```


```{r}
# Getting rid of all other BIA shapes
beach_bia <- BIA_data %>% filter(AREA_NA8 == "The Beach")

# Converting data from iNaturalist into sf
inaturalist_df <- inaturalist_df %>%
  mutate(
    lon = as.numeric(longitude),
    lat = as.numeric(latitude)
  ) %>%
  filter(!is.na(longitude),
         !is.na(latitude),
         lon >= -180,
         lon <= 180,
         lat >= -90,
         lat <= 90)

obs_sf <- st_as_sf(inaturalist_df, coords = c("longitude", "latitude"), crs = 4326)
```


```{r}
# Looking at water bodies
leaflet() %>% addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = water,
              label = ~OBJECTID)
```


```{r}
# Isolating Glen Stewart Ravine
glen_rav <- water %>% filter(OBJECTID == 446)

# Adding buffer around ravine
glen_utm <- st_transform(glen_rav, 32617)
glen_buffer_utm <- st_buffer(glen_utm, dist = 20)
glen_buffer <- st_transform(glen_buffer_utm, crs = 4326)

leaflet() %>% addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = glen_buffer,
              label = "Glen Stewart Ravine")
```


```{r}
# Displaying trees on the map
leaflet() %>% addProviderTiles("CartoDB.Positron") %>%
  addCircles(data = trees,
             opacity = 1,
             radius = 1)
```


```{r}
# Displaying all the shapes
leaflet() %>% addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = beach_bia,
              label = ~AREA_NA8,
              fillOpacity = 0.1,
              weight = 2) %>% 
  addPolygons(data = beach_park,
              label = "Woodbine Beach/Park",
              fillColor = "pink",
              color = "red",
              weight = 2) %>% 
  addCircleMarkers(data = obs_sf,
                   label = ~scientific_name,
                   color = "blue",
                   opacity = 1,
                   radius = 1) %>% 
  addCircleMarkers(data = trees,
                   color = "green",
                   opacity = 1,
                   radius = 1)
```


```{r}
# Only interested in iNaturalist observations within areas of interested
polys <- bind_rows(beach_bia, beach_park, glen_buffer)
obs_within <- st_filter(obs_sf, polys, .predicate = st_within)

# Only interested in trees within areas of interest
trees_within <- st_filter(trees, polys, .predicate = st_within)
```


```{r}
# Mapping everything together
leaflet() %>% addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = beach_bia,
              group = "BIA street",
              label = ~AREA_NA8,
              fillOpacity = 0.1,
              weight = 2) %>% 
  addPolygons(data = beach_park,
              label = "Woodbine Beach/Park",
              group = "Park/Beach",
              fillColor = "red",
              color = "red",
              weight = 2) %>% 
  addPolygons(data = glen_buffer,
              label = "Glen Stewart Ravine",
              group = "Ravine",
              fillOpacity = 0.4,
              fillColor = "purple",
              color = "purple",
              weight = 2) %>% 
  addCircles(data = obs_within,
             group = "iNaturalist",
             color = "blue",
             label = ~scientific_name,
             opacity = 1,
             radius = 1,
             weight = 4) %>% 
  addCircles(data = trees_within,
             group = "Trees",
             color = "green",
             opacity = 1,
             radius = 1,
             weight = 4) %>% 
  addLegend(position = "bottomright",
            colors = c("blue", "green", "purple"),
            labels = c("iNaturalist Observations", "Trees", "Ravine"),
            title = "Legend",
            opacity = 1) %>% 
  addLayersControl(position = "topright",
                   overlayGroups = c("Trees", "iNaturalist",
                                     "BIA street", "Park/Beach",
                                     "Ravine"),
                   options = layersControlOptions(collapsed = FALSE))
```


```{r}
# Categorizing iNaturalist observations
m <- leaflet() %>% addProviderTiles("CartoDB.Positron")


# There are two observations without this information
s <- subset(obs_within, iconic_taxon_name == "")

# Manually changing these observations
s_names <- c("Nostoc commune", "Nostoc pruniforme")

obs_within <- obs_within %>% 
  mutate(iconic_taxon_name = if_else(scientific_name %in% s_names,
                                     "Cyanophyceae", iconic_taxon_name))

obs_within$iconic_taxon_name <- as.factor(obs_within$iconic_taxon_name)

groups <- levels(obs_within$iconic_taxon_name)

species_cat.pal <- colorFactor("viridis", domain = groups)

for (g in groups) {
  m <- m %>% addCircles(data = subset(obs_within, iconic_taxon_name == g),
                        group = g,
                        label = g,
                        color = ~species_cat.pal(g),
                        radius = 1,
                        opacity = 1,
                        weight = 4)
}

m %>% addLayersControl(overlayGroups = groups,
                       options = layersControlOptions(collapsed = FALSE)
                       ) %>% 
  addLegend("bottomleft", pal = species_cat.pal,
            values = obs_within$iconic_taxon_name,
            opacity = 1)
```


```{r}
# Defined new BIA areas
the_beaches <- nbhd %>% filter(X_id1 == 93)

leaflet() %>% addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data=the_beaches)
```


```{r}

```

