---
title: "STA490_311Complaints_Bike"
output: html_document
date: "2025-11-17"
---
```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(stringr)
```

```{r}
# get all data from 2022-2025
files <- list.files(pattern = "^SR.*\\.csv$")

df <- files %>%
  lapply(read.csv) %>%
  bind_rows()

df
```

```{r}
# filter data in beach bia area
df_beach <- df %>%
  filter(First.3.Chars.of.Postal.Code == "M4E" |
         First.3.Chars.of.Postal.Code == "M4L" |
         First.3.Chars.of.Postal.Code == "M4M")

df_beach
```

```{r}
# get monthly bike-related data
bike_monthly <- df %>%
  # only contain "bike" or "bicy"
  filter(str_detect(Service.Request.Type,
                    regex("bike|bicy", ignore_case = TRUE))) %>%
  # get month
  mutate(
    Creation.Date = parse_date_time(
      Creation.Date,
      orders = c("Ymd HMS", "Y-m-d HMS", "Y-m-d HM", "Y-m-d",
                 "mdY HMS", "mdY HM", "mdY")
    ),
    year_month = floor_date(Creation.Date, "month")
  ) %>%
  count(year_month, name = "n")    # total count of every month

bike_monthly
```

```{r}
# draw plot of trend
ggplot(bike_monthly, aes(x = year_month, y = n)) +
  geom_line() +
  labs(
    title = "Monthly total bike-related 311 service requests",
    x = "Month",
    y = "Number of bike-related requests"
  ) +
  theme_minimal(base_size = 13)
```

```{r}
# get trend for each year
bike_monthly_yearly <- df %>%
  filter(str_detect(Service.Request.Type,
                    regex("bike|bicy", ignore_case = TRUE))) %>%
  mutate(
    Creation.Date = parse_date_time(
      Creation.Date,
      orders = c("Ymd HMS","Y-m-d HMS","Y-m-d HM","Y-m-d",
                 "mdY HMS","mdY HM","mdY")
    ),
    Year  = year(Creation.Date),
    Month = month(Creation.Date)
  ) %>%
  count(Year, Month, name = "n") %>%
  arrange(Year, Month)

bike_monthly_yearly

ggplot(bike_monthly_yearly,
       aes(x = Month, y = n, group = Year, colour = as.factor(Year))) +
  geom_line(size = 1) +
  geom_point() +
  facet_wrap(~ Year, scales = "free_y") +
  scale_x_continuous(breaks = 1:12) +
  labs(
    title = "Monthly Bike-related 311 Requests by Year",
    x = "Month",
    y = "Number of Bike-related Requests",
    colour = "Year"
  ) +
  theme_minimal(base_size = 13)

```


```{r}
# get all different Service Request Types about bike
df %>%
  filter(str_detect(Service.Request.Type, regex("bike|bicy", ignore_case = TRUE))) %>%
  distinct(Service.Request.Type)

```

```{r}
# get all bike-related data
bike_df <- df %>%
  filter(str_detect(Service.Request.Type, regex("bike|bicy", ignore_case = TRUE)))

bike_df
```

```{r}
# count for each type
bike_counts <- bike_df %>%
  count(Service.Request.Type, sort = TRUE)

print(bike_counts)
```

```{r}
# categorize these into 3 major categories
bike_df <- bike_df %>%
  mutate(
    Bike_Category = case_when(
      # Abandoned bikes / bike removal
      Service.Request.Type %in% c(
        "Complaint/Investigation -Abandoned Bikes",
        "Complaint - Abandoned Bikes in Rideable Condition",
        "Litter / Bike Removal Inquiry",
        "Bike Removal and Lost Bike Inquiry"
      ) ~ "Abandoned bikes / bike removal",

      # Bike lane winter maintenance
      Service.Request.Type %in% c(
        "Bike Lane Winter Maintenance Required",
        "Bike Lane - Winter Maintenance Required"
      ) ~ "Bike lane winter maintenance",

      # Bike lane damage (potholes, barriers)
      Service.Request.Type %in% c(
        "Bike Lane Pothole",
        "Damaged Bike Lane Barrier",
        "Bicycle Stand (Post and Ring) Repair or Graffiti Removal",
        "Bicycle Signals"
      ) ~ "Bike lane damage (potholes, barriers)",

      TRUE ~ "Other bike-related"
    )
  )

bike_df %>%
  count(Bike_Category, Service.Request.Type)
```

```{r}
# get count for each category
bike_df %>%
  count(Bike_Category, name = "count") %>%
  ggplot(aes(x = count,
             y = reorder(Bike_Category, count))) +
  
  geom_col(fill = "steelblue", width = 0.45) +

  geom_text(aes(label = count),
            hjust = -0.2,      # 往右移动一点
            size = 5,
            color = "black") +
  
  scale_x_continuous(expand = expansion(mult = c(0, 0.2))) +
  
  labs(
    title = "Bike-related 311 Requests by Category",
    x = "Count",
    y = NULL
  ) +
  
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 12)
  )
```

```{r}
# time trend for 3 major categories for 2025
bike_2025 <- bike_df %>%
  mutate(
    Creation.Date = as.Date(Creation.Date),
    year = year(Creation.Date),
    month = floor_date(Creation.Date, "month")
  ) %>%
  filter(year == 2025) %>%
  count(month, Bike_Category, name = "count")

ggplot(bike_2025,
       aes(x = month, y = count, colour = Bike_Category)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 2) +
  labs(
    title = "Monthly Bike-related 311 Requests by Category (2025)",
    x = "Month",
    y = "Number of Requests",
    colour = "Category"
  ) +
  scale_x_date(date_labels = "%b") +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    legend.position = "bottom"
  )
```

```{r}
# time trend for 3 major categories from 2022-2025
ggplot(bike_monthly_cat,
       aes(x = year_month, y = count, colour = Bike_Category)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1.8) +
  labs(
    title = "Monthly Bike-related 311 Requests by Category",
    x = "Month",
    y = "Number of Requests",
    colour = "Category"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    legend.position = "bottom"
  )
```