---
title: "Biodiversity Comparison EDA"
author: "Derek Li"
date: "2026-02-02"
output: html_document
---


```{r}
library(sf)
library(leaflet)
library(dplyr)
library(spatstat)
library(terra)
library(htmlwidgets)
library(vegan)
library(ggplot2)
library(tidyr)
library(knitr)
```

```{r}
# Loading the data
# Toronto Open Data
nbhd  <- st_read("../../../Data/neighbourhoods/Neighbourhoods - 4326.shp")

trees <- st_read("../../../Data/trees/TOPO_TREE_WGS84.shp")
hp_trees <- st_read("../../../Data/trees_HP/High_Park_Tree.shp")

water <- st_read("../../../Data/waterbodies/TOPO_Waterbody_WGS84.shp")

green <- st_read("../../../Data/greenspace/Green Spaces - 4326.shp")

bia   <- st_read("../../../Data/bia/Business Improvement Areas Data - 4326.shp")

# iNaturalist data
inaturalist_df <- read.csv("../../../Data/inaturalist/observations.csv")
inaturalist_hp <- read.csv("../../../Data/inaturalist_hp/observations.csv")
```


```{r}
# Areas of interest
beach_BIA <- nbhd %>% filter(X_id1 == 93)
high_park <- nbhd %>% filter(AREA_SH5 == "087")
```


```{r}
# Converting iNaturalist into usable shapefile
inaturalist_df <- inaturalist_df %>%
  mutate(
    lon = as.numeric(longitude),
    lat = as.numeric(latitude)
  ) %>%
  filter(!is.na(longitude),
         !is.na(latitude),
         lon >= -180,
         lon <= 180,
         lat >= -90,
         lat <= 90)

obs_sf <- st_as_sf(inaturalist_df, coords = c("longitude", "latitude"), 
                   crs = 4326)

# Shapefile with only observations within boundaries
obs_sf <- st_filter(obs_sf, beach_BIA, .predicate = st_within)

inaturalist_hp <- inaturalist_hp %>% 
  mutate(
    lon = as.numeric(longitude),
    lat = as.numeric(latitude)
  ) %>%
  filter(!is.na(longitude),
         !is.na(latitude),
         lon >= -180,
         lon <= 180,
         lat >= -90,
         lat <= 90)

obs_hp <- st_as_sf(inaturalist_hp, coords = c("longitude", "latitude"),
                   crs = 4326)

# Shapefile with only observations within High Park neighbourhood
obs_hp <- st_filter(obs_hp, high_park, .predicate = st_within)
```


```{r}
# Adding category column
obs_sf <- obs_sf %>% mutate(category = case_when(
  iconic_taxon_name == "Plantae" ~ "Plants",
  iconic_taxon_name == "Aves" ~ "Birds",
  iconic_taxon_name == "Insecta" ~ "Insects",
  iconic_taxon_name == "Mammalia" ~ "Mammals",
  iconic_taxon_name == "Reptilia" ~ "Reptiles",
  iconic_taxon_name == "Arachnida" ~ "Spiders",
  TRUE ~ "Other"))

obs_sf$category <- as.factor(obs_sf$category)

obs_hp <- obs_hp %>% mutate(category = case_when(
  iconic_taxon_name == "Plantae" ~ "Plants",
  iconic_taxon_name == "Aves" ~ "Birds",
  iconic_taxon_name == "Insecta" ~ "Insects",
  iconic_taxon_name == "Mammalia" ~ "Mammals",
  iconic_taxon_name == "Reptilia" ~ "Reptiles",
  iconic_taxon_name == "Arachnida" ~ "Spiders",
  TRUE ~ "Other"))

obs_hp$category <- as.factor(obs_hp$category)
```


```{r}
# Filtering the Toronto data sets
trees_BIA <- st_filter(trees, beach_BIA, .predicate = st_within)
trees_HP <- st_filter(hp_trees, high_park, .predicate = st_within)

water_BIA <- st_filter(water, beach_BIA, .predicate = st_within)
water_HP <- st_filter(water, high_park, .predicate = st_within)

green_BIA <- st_filter(green, beach_BIA, .predicate = st_within)
green_HP <- st_filter(green, high_park, .predicate = st_within)

bia_strip <- bia %>% filter(X_id1 == 10)
```


### Overall Species Richness

```{r}
beach_count <- obs_sf %>% st_drop_geometry() %>% count(scientific_name)
hp_count <- obs_hp %>% st_drop_geometry() %>% count(scientific_name)

div_func <- function(x, name) {
  n_obs = sum(x$n)
  richness = n_distinct(x$scientific_name)
  shannon = diversity(x$n, index = "shannon")
  return(c(name,
           n_obs,
           richness,
           shannon,
           diversity(x$n, index = "simpson"),
           shannon / log(richness)))
}

div_res <- data.frame(rbind(div_func(beach_count, "BIA"),
                            div_func(hp_count, "High Park")))
colnames(div_res) <- c("Area",
                           "# of obs",
                           "richness",
                           "Shannon index",
                           "Simpson index",
                           "Evenness")
div_res
```


### Species richness of green spaces

```{r}
High_Park <- green_HP %>% filter(AREA_NA9 == "HIGH PARK")
Kew <- green_BIA %>% filter(AREA_NA9 == "KEW GARDENS")
Glen <- green_BIA %>% filter(AREA_NA9 == "GLEN STEWART PARK")
Woodbine <- green_BIA %>% filter(AREA_NA9 == "WOODBINE PARK")
```


```{r}
green_count <- function(x, hp = TRUE) {
  if (hp) {
    obs = st_filter(obs_hp, x, .predicate = st_within)
  } else {
    obs = st_filter(obs_sf, x, .predicate = st_within)
  }
  
  return(obs %>% st_drop_geometry() %>% count(scientific_name))
}

div_res <- data.frame(rbind(div_func(green_count(High_Park), "High Park"),
                            div_func(green_count(Kew, hp = FALSE), "Kew Gardens"),
                            div_func(green_count(Glen, hp = FALSE), "Glen Stewart Park"),
                            div_func(green_count(Woodbine, hp = FALSE), "Woodbine Park")))
colnames(div_res) <- c("Area",
                       "# of obs",
                       "richness",
                       "Shannon index",
                       "Simpson index",
                       "Evenness")
kable(div_res)
```


```{r}
# projecting polygons
nb <- st_transform(beach_BIA, crs = 32617)
hp <- st_transform(high_park, crs = 32617)

div_density <- function(x, y) {
  obs <- st_filter(y, x, .predicate = st_within)
  proj <- st_transform(x, crs = 32617)
  area <- as.numeric(st_area(proj)) / 1e+6
  n <- nrow(obs)
  richness = n_distinct(obs$scientific_name)
  
  return(c(x$AREA_NA9,
           n / area,
           richness / n))
}

div_density_res <- data.frame(rbind(div_density(High_Park, obs_hp), 
                                    div_density(Kew, obs_sf),
                                    div_density(Glen, obs_sf),
                                    div_density(Woodbine, obs_sf)))
colnames(div_density_res) <- c("Green space",
                               "Observations per km2",
                               "Richness to observation ratio")
kable(div_density_res)
```


### Species Richness Relative to Natural Features

```{r}
# projecting all the shapefiles
trees_pr <- st_transform(trees_BIA, 32617)
trees_hp_pr <- st_transform(trees_HP, 32617)

water_pr <- st_transform(water_BIA, 32617)
water_hp_pr <- st_transform(water_HP, 32617)

green_pr <- st_transform(green_BIA, 32617)
green_hp_pr <- st_transform(green_HP, 32617)

obs_pr <- st_transform(obs_sf, 32617)
obs_hp_pr <- st_transform(obs_hp, 32617)
```


```{r}
w <- as.owin(nb)

coords <- st_coordinates(trees_pr)

X <- ppp(x = coords[,1],
         y = coords[,2],
         window = w)

D <- density.ppp(X,
                 sigma = bw.diggle(X),
                 edge = TRUE)

D_km2 <- eval.im(D * 1e6)
plot(D_km2, main = "Trees in The Beaches neighbourhood (trees per km2)")
```


```{r}
trees_strip <- st_filter(trees_BIA, bia_strip, .predicate = st_within)
trees_strip_proj <- st_transform(trees_strip, crs = 32617)
bia_strip_proj <- st_transform(bia_strip, crs = 32617)
coords <- st_coordinates(trees_strip_proj)

w <- as.owin(bia_strip_proj)
X <- ppp(x = coords[,1],
         y = coords[,2],
         window = w)
plot(X, main = "Point pattern in window")

D <- density.ppp(X,
                 sigma = bw.diggle(X),
                 edge = TRUE)
D_km2 <- eval.im(D * 1e6)

plot(D_km2, main = "Trees in Beach BIA (trees per km2)")
```



